import * as yaml from 'yaml';

// Initial YAML content
export const initialYamlContent = `#Generated by NGFacade
ingestion:
  kafka-to-iceberg:
    pipelines:
      alex_condition_test:
        enabled: true
        transformation: |-
          let level_0 = (.)
          flatten([
          for (if(.pricings) .pricings else [null])
          let level_1 = (.)
          {
          "appliedat": floor(number($level_0.appliedAt)),
          "boolean_condition": if ($level_0.condition == true and $level_0.condition == false and $level_0.condition and not($level_0.condition)) null else true,
          "business_date": floor(number($level_0.backgroundImage)),
          "business_ts": floor(number($level_0.backgroundImage)),
          "condition": $level_0.condition,
          "createdat": floor(number($level_0.createdAt))*1000,
          "id": $level_0.id,
          "int_appliedat": $level_0.int_appliedAt,
          "int_createdat": $level_0.int_createdAt*1000,
          "long_condition": if ($level_0.styleTitle > 1 and $level_0.styleTitle < 2 and $level_0.styleTitle >= 123 and $level_0.styleTitle <= 321 and $level_0.styleTitle and not($level_0.styleTitle)) 123 else 54321,
          "num_appliedat": floor($level_0.num_appliedAt),
          "num_createdat": floor($level_0.num_createdAt)*1000,
          "pricings_abfeature": $level_1.abFeature,
          "pricings_currency": $level_1.currency,
          "pricings_price": $level_1.price,
          "sceneobjecttypes": join($level_0.sceneObjectTypes, ","),
          "string_condition": if ($level_0.id == "1" and $level_0.id != "2" and contains("123", $level_0.id) and $level_0.id and not($level_0.id) and $level_0.id == "") lowercase($level_0.title) else "some_random_value",
          "styletitle": $level_0.styleTitle,
          "tags": join($level_0.tags, ","),
          "thumbimage": $level_0.thumbImage,
          "title": $level_0.title,
          "updatedat": parse-timestamp($level_0.updatedAt, "yyyy-MM-dd")
          }
          ])
        source:
          topic: facade_alex_condition_test
        target:
          table-schema: "\${main.schemas.alex_condition_test}"
        deduplication:
          enabled: true
          allow-nullable-key-fields: true`;

// Format YAML content
export const formatYaml = (content) => {
  try {
    const parsed = yaml.parse(content);
    return yaml.stringify(parsed, { indent: 2 });
  } catch (error) {
    throw new Error(`Failed to format YAML: ${error.message}`);
  }
};

// Parse YAML and return errors
export const parseYaml = (content) => {
  try {
    yaml.parse(content);
    return { valid: true, errors: [] };
  } catch (error) {
    // Ensure line number is valid (1-based)
    const line = error.line || 1;
    const column = error.col || 1;
    
    return { 
      valid: false, 
      errors: [{ 
        message: error.message, 
        line: Math.max(1, line), // Ensure line is at least 1
        column: Math.max(1, column) // Ensure column is at least 1
      }] 
    };
  }
};

// Custom linting rules
export const customLintRules = (content) => {
  const errors = [];
  const lines = content.split('\n');
  
  lines.forEach((line, lineIndex) => {
    // Check for camelCase keys (custom rule)
    const camelCaseRegex = /^(\s*)([a-z][a-zA-Z0-9]*[A-Z][a-zA-Z0-9]*):/;
    const match = line.match(camelCaseRegex);
    
    if (match) {
      const key = match[2];
      const suggestedKey = key.replace(/([A-Z])/g, '_$1').toLowerCase();
      
      errors.push({
        from: lineIndex,
        to: lineIndex + 1,
        severity: 'warning',
        message: `Key "${key}" uses camelCase. Consider using snake_case: "${suggestedKey}"`,
        line: lineIndex + 1,
        column: match[1].length + 1,
        fix: {
          from: match[1].length + 1,
          to: match[1].length + 1 + key.length,
          insert: suggestedKey
        }
      });
    }
    
    // Check for missing commas in arrays/objects
    const missingCommaRegex = /^(\s*)([^#\s][^:]*):\s*([^,\s][^,\n]*)$/;
    const commaMatch = line.match(missingCommaRegex);
    
    if (commaMatch && !line.trim().endsWith(',') && !line.trim().endsWith('|') && !line.trim().endsWith('-')) {
      const nextLine = lines[lineIndex + 1];
      if (nextLine && nextLine.trim() && !nextLine.trim().startsWith('#')) {
        errors.push({
          from: lineIndex,
          to: lineIndex + 1,
          severity: 'error',
          message: 'Missing comma at end of line',
          line: lineIndex + 1,
          column: line.length,
          fix: {
            from: line.length,
            to: line.length,
            insert: ','
          }
        });
      }
    }
    
    // Check for wrong indentation
    const indentationRegex = /^(\s*)(.+)$/;
    const indentMatch = line.match(indentationRegex);
    
    if (indentMatch && line.trim()) {
      const spaces = indentMatch[1].length;
      if (spaces % 2 !== 0 && spaces > 0) {
        errors.push({
          from: lineIndex,
          to: lineIndex + 1,
          severity: 'error',
          message: 'Incorrect indentation. YAML uses 2 spaces per level',
          line: lineIndex + 1,
          column: 1,
          fix: {
            from: 0,
            to: spaces,
            insert: ' '.repeat(Math.round(spaces / 2) * 2)
          }
        });
      }
    }
  });
  
  return errors;
};

// Combine standard YAML parsing with custom rules
export const lintYaml = (content) => {
  const standardErrors = parseYaml(content);
  const customErrors = customLintRules(content);
  
  return {
    valid: standardErrors.valid,
    errors: [...standardErrors.errors, ...customErrors]
  };
};

// Apply a fix to the content
export const applyFix = (content, fix) => {
  if (!fix || typeof fix !== 'object') {
    console.warn('Invalid fix object:', fix);
    return content;
  }

  const lines = content.split('\n');
  
  // Handle line-based fixes
  if (fix.line !== undefined && fix.line > 0 && fix.line <= lines.length) {
    const lineIndex = fix.line - 1;
    const line = lines[lineIndex];
    
    if (fix.from !== undefined && fix.to !== undefined && fix.insert !== undefined) {
      const newLine = line.substring(0, fix.from) + fix.insert + line.substring(fix.to);
      lines[lineIndex] = newLine;
      return lines.join('\n');
    }
  }
  
  // Handle character-based fixes (for CodeMirror)
  if (fix.from !== undefined && fix.to !== undefined && fix.insert !== undefined) {
    const before = content.substring(0, fix.from);
    const after = content.substring(fix.to);
    return before + fix.insert + after;
  }
  
  console.warn('Fix object missing required properties:', fix);
  return content;
}; 